config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
      resources :prescriptions
      resources :categories
      resources :appointments
      resources :doctors
      resources :admin_users

      root to: "admin_users#index"
    end
  get 'admin_users/index'
  get 'admin_users/show'
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    passwords: 'admin_users/passwords',
    registrations: 'admin_users/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  devise_for :doctors, controllers: {
    sessions: 'doctors/sessions',
    passwords: 'doctors/passwords',
    registrations: 'doctors/registrations'
  }

  resources :users
  resources :doctors
  resources :appointments
  resources :prescriptions
  resources :admin_users
  

  unauthenticated do
    root "home#index"
  end

  authenticated :doctor do
    root 'doctors#index', as: :authenticated_doctor_root
  end

  authenticated :user do
    root 'users#index', as: :authenticated_user_root
  end

  authenticated :admin_user do
    root 'admin_users#index', as: :authenticated_admin_user_root
  end
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :appointment

  validates :prescript, presence: true, length: { in: 1..650 }
end

app/controllers/admin/prescriptions_controller.rb
module Admin
  class PrescriptionsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :authenticate_doctor!, only: %i[create destroy]

  def index
    @user = current_doctor
    @appointments = @user.appointments
    appointments_ids = @appointments.map(&:id)
    @prescriptions = Prescription.where(appointment_id: appointments_ids)
  end

  def show
    @user = current_doctor || current_user
    @prescription = Prescription.find(params[:id])
    @appointment = Appointment.find(@prescription.appointment_id)
  end

  def new
    @user = current_doctor
    @appointment = Appointment.find_by(id: params[:appointment_id])
    @prescription = Prescription.new
  end

  def create
    @user = current_doctor || current_user
    @appointment = Appointment.find_by(id: params[:appointment_id])
    @prescription = Prescription.new(prescription_params)

    if @prescription.save
      redirect_to prescriptions_path
      flash[:notice] = 'Your prescription was successfully created'
    else
      render :new, alert: 'An error has occurred while creating a prescription'
    end
  end

  def destroy
    @prescription = Prescription.find(params[:id])
    @prescription.destroy!
    redirect_to prescriptions_path(current_doctor.id), notice: 'Recommendation was deleted successfully!'
  end

  private

  def prescription_params
    params.require(:prescription).permit(:prescript, :appointment_id)
  end
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/prescriptions/_form.html.erb
    <%= form_with model: @prescription, url: prescriptions_path, class: "card left" do |form| %>    
      <%
=begin%>
 <p class="m-2 p-1">Write your prescript for patient: <strong><%= @appointment.user.full_name %></strong></p>         
<%
=end%>
      <%
=begin%>
 <%= form.hidden_field :appointment_id,  value: @appointment.id%>  <br>   
<%
=end%>
      
      <%= form.label :prescript, class: "m-1" %> <br>
      <%= form.text_area :prescript , cols: 30, rows: 10 %> <br>
      <%= form.submit "Submit", class: 'pure-button button-secondary mb-2' %>    
    <% end %>  

app/views/prescriptions/index.html.erb
<%= link_to doctor_path(@user.id), class: "btn btn-link" do %>
  <p class="link-black text-center"><strong>back to profile</strong></p>
<% end %>
<h1>All Prescriptions</h1>

<% if @appointments.blank? %>
  <h4>There are not prescriptions yet</h4>
<% else %>
  <div class="d-flex gap-3 flex-wrap mt-5">
    <% @appointments.each do |a| %>
      <div class="card p-2">
        <div class="card-body">
          <% if a.prescription.blank? %>
            <%= ' ' %>
          <% else %>
            <p>Prescription for: <strong><%= a.user.full_name  %></strong></p>
            <p><%= a.prescription.prescript %></p>
          <%end%>
        </div>
      </div>
    <%end%>
  <%end%>
</div>

app/views/prescriptions/new.html.erb
<%= link_to doctor_path(@user.id), class: "btn btn-link" do %>
    <p class="link-black text-center"><strong>back</strong></p>
<% end %>


<section>
  <h1 class="text-center">Add a new prescription</h1>
    
  <%= form_with model: @prescription, url: prescriptions_path, class: "card left" do |form| %>    
      <p class="m-2 p-1">Write your prescript for patient: <strong><%= @appointment.user.full_name %></strong></p>        
      <%= form.hidden_field :appointment_id,  value: @appointment.id%>  <br>  
      
      <%= form.label :prescript, class: "m-1" %> <br>
      <%= form.text_area :prescript , cols: 30, rows: 10 %> <br>
      <%= form.submit "Submit", class: 'pure-button button-secondary mb-2' %>    
  <% end %>  
</section>

app/views/prescriptions/show.html.erb
<% if current_user %>
<%= link_to user_path(@user.id), class: "btn btn-link" do %>
    <p class="link-black text-center"><strong>back to profile</strong></p>
  <% end %>
  <% else %>
<%= link_to doctor_path(@user.id), class: "btn btn-link" do %>
    <p class="link-black text-center"><strong>back to profile</strong></p>
  <% end %>
  <% end %>


<h1>Your Prescription</h1>

<h6>Recommendation from doctor: <strong><%= @appointment.doctor.full_name %></strong></h6>
<p><%= @prescription.prescript %></p>

<% if current_doctor %>
<div class="">
  <%= button_to "Delete this recommendation", @prescription, 'method': :delete, class: 'btn btn-danger text-light rounded-2 my-2' %>     
</div> 
<% end %>