config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
      resources :prescriptions
      resources :categories
      resources :appointments
      resources :doctors
      resources :admin_users

      root to: "admin_users#index"
    end
  get 'admin_users/index'
  get 'admin_users/show'
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    passwords: 'admin_users/passwords',
    registrations: 'admin_users/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  devise_for :doctors, controllers: {
    sessions: 'doctors/sessions',
    passwords: 'doctors/passwords',
    registrations: 'doctors/registrations'
  }

  resources :users
  resources :doctors
  resources :appointments
  resources :prescriptions
  resources :admin_users
  

  unauthenticated do
    root "home#index"
  end

  authenticated :doctor do
    root 'doctors#index', as: :authenticated_doctor_root
  end

  authenticated :user do
    root 'users#index', as: :authenticated_user_root
  end

  authenticated :admin_user do
    root 'admin_users#index', as: :authenticated_admin_user_root
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    case user
    when AdminUser
      can :manage, :all
    when Doctor
      can :manage, Prescription, Appointment
      can :read, :all
    when User
      can :manage, Appointment
      can :read, :all
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :phone, uniqueness: true

  def email_required?
    false
  end
       
  def email_changed?
    false
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :user
  has_one :prescription, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :doctor, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :category
  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments
  has_one_attached :attachment

  validates :phone, presence: true, uniqueness: true
  validates :full_name, presence: true

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :appointment

  validates :prescript, presence: true, length: { in: 1..650 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointments

  validates :phone, presence: true, uniqueness: true
  validates :full_name, presence: true

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
    before_action :authenticate_admin!
    def index
        @admin = current_admin.id
      end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate_doctor!
  def index
    @doctor = current_doctor
  end

  def show
    @appointments = Appointment.where(doctor_id: current_doctor.id)
    @prescriptions = Prescription.where(appointment_id: current_doctor.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  load_and_authorize_resource

  def index
    @user = current_user
  end

  def show
    @user = current_user
    @display_doctors = appointments_count
  end

  def appointments_count
    doctors = Doctor.all
    @appointments = Appointment.all
    @valid_doctors = []
    doctors.each do |doctor|
      if @appointments.where(doctor_id: doctor.id).count < 11
        @valid_doctors << doctor
      else
        @valid_doctors.delete(doctor)
      end
    end
    @valid_doctors.uniq
  end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="container-fluid d-flex flex-column align-items-center bg-secondary p-3">

   <div class="header">
     <h1 class="text-center display-2">Healthcare Center</h1>
   </div>

  <div class="content">
    <h2 class="text-center display-4 text-warning">Welcome to our Healthcare Center application</h1>
    <p class="text-even fs-5 text-white">The purpose of this application is to provide interaction between doctors and patients. In particular, the patient can register, enter the public page, go to his profile, select the specialist he wants to contact and make an appointment. In turn, the doctor with whom the patient made an appointment can enter his profile through the public page and leave his recommendations online to the patient, after which the appointment is considered closed. General management is carried out by the administrator.</p>
    <div class="content-subhead">
      <p class="m-2 text-start fs-5 text-white">You can enter the application by following the links below:</p>
      <div class="container-fluid d-flex justify-content-center p-3">  
        <p class="m-2 p-1 fw-bold">For doctors:</p>
        <%= link_to "Doctor Signin", new_doctor_session_path, class: "btn btn-success text-light fw-bold" %>
        <p class="m-2 p-1 fw-bold">For patients:</p>
        <%= link_to "Patient Signin", new_user_session_path, class: "btn btn-primary text-light fw-bold" %>
        <p class="m-2 p-1 fw-bold">For admins:</p>
        <%= link_to "Admin Signin", new_admin_user_session_path, class: "btn btn-warning text-light fw-bold" %>  
      </div>
    </div>

    <div class="content-subhead">
      <p class="m-2 text-start fs-5 text-warning">Patients can register here:</p>     
      <%= link_to "Patient Signup", new_user_registration_path, class: "btn btn-danger text-light fw-bold" %>
    </div>  
    </div>  
</div> 